# Generated by Django 3.1 on 2021-04-11 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_home_app.clientmodel')),
            ],
            options={
                'db_table': 'house',
            },
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type_and_count', models.CharField(max_length=50)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_home_app.housemodel')),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=512)),
                ('original_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('product_link', models.CharField(max_length=255)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_home_app.roommodel')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
